#!/usr/bin/env bash

sudo apt install -y build-essential lua5.4 luarocks fd-find ripgrep llvm clangd

# rm -rf $XDG_DATA_HOME/software/neovim
# git clone -b "release-0.12" --depth 1 https://github.com/neovim/neovim.git $XDG_DATA_HOME/software/neovim
# pushd $XDG_DATA_HOME/software/neovim > /dev/null
# make CMAKE_BUILD_TYPE=RelWithDebInfo
# sudo make install
# popd > /dev/null

rm $HOME/.local/bin/lua-language-server
rm -rf $XDG_DATA_HOME/software/lua-language-server
mkdir -p $XDG_DATA_HOME/software/lua-language-server
pushd $XDG_DATA_HOME/software/lua-language-server > /dev/null
curl -L -O https://github.com/LuaLS/lua-language-server/releases/download/3.18.2/lua-language-server-3.18.2-linux-x64.tar.gz
tar -xf lua-language-server-3.18.2-linux-x64.tar.gz -av 
ln -s $XDG_DATA_HOME/software/lua-language-server/bin/lua-language-server $HOME/.local/bin/lua-language-server
popd > /dev/null

sudo luarocks install luacheck
